name: "Merge Dependabot Pull Request"
description: "Automatically Merge Dependabot Pull Request"
runs:
  using: "composite"
  steps:
    - name: Check out repo
      uses: actions/checkout@v2.4.0
    - name: auto-merge
      if: |
        github.actor == 'dependabot[bot]' &&
        github.event_name == 'pull_request'
      run: |
        gh pr merge --auto --rebase "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        # this secret needs to be in the settings.secrets.dependabot
        GITHUB_TOKEN: ${{secrets.GH_ACTION_TOKEN}}
      shell: bash
