name: FormatJava
on:
  push:
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        java: ['11']
        os: [ ubuntu ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn package -DskipTests=true
      - name: Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "a   reformat code" -a  || echo "nothing to commit"
          remote="https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
          branch="${GITHUB_REF:11}"
          git push "${remote}" ${branch} || echo "nothing to push"
        shell: bash
