name: Publish ApprovalTests.Java to Maven Central

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: set version
        run: mvn versions:set -DnewVersion=10.0.0

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}

      - name: set snapshot version
        run: mvn versions:set -DnewVersion=10.0.1-SNAPSHOT

      - name: Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "e set SNAPSHOT version" -a  || echo "nothing to commit"
          remote="https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
          branch="${GITHUB_REF:11}"
          git push "${remote}" ${branch} || echo "nothing to push"
        shell: bash
